### ISSUE TITLE
Seems like the handle-request/ folder has been moved/renamed?

### ISSUE THREAD

**Issue by kostasx** [DeNepo/study-lenses#11]
https://github.com/DeNepo/study-lenses/blob/934baa5e8d3d1ecd79a1de3f0705850a1490c957/README.md?plain=1#L210

Even though the docs mention about a `handle-request` dir, such a thing does not currently exist. Was it removed/renamed?

**Comment by colevandersWands** [comment]
good spot, very stale docs.  `server/study.js` now handles most of the study-lenses specific work.  `server/index.js` has the more generic stuff like static serving and falling back to index.html/README.md if a folder is requested without a path.
